
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class login1 extends javax.swing.JFrame {
    Connection connect = null;

    /**
     * Creates new form login1
     */
    public login1() {
        initComponents();
        connect = dbms.dbconnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        pass1 = new javax.swing.JPasswordField();
        user = new javax.swing.JTextField();
        checkbox = new javax.swing.JCheckBox();
        login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        name.setForeground(new java.awt.Color(204, 0, 51));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("User Login");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 442, -1));

        signup.setBackground(new java.awt.Color(204, 204, 204));
        signup.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signup.setText("Sign Up");
        signup.setBorder(null);
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 160, 40));

        pass1.setBorder(null);
        pass1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass1FocusLost(evt);
            }
        });
        pass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass1ActionPerformed(evt);
            }
        });
        getContentPane().add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 300, 40));

        user.setBorder(null);
        user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userFocusLost(evt);
            }
        });
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 300, 40));

        checkbox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkbox.setText("Show password");
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });
        getContentPane().add(checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 160, 20));

        login.setBackground(new java.awt.Color(204, 204, 204));
        login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        login.setText("Login");
        login.setBorder(null);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 160, 40));

        setSize(new java.awt.Dimension(565, 335));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed
        if(checkbox.isSelected()){
            pass1.setEchoChar((char)0);
        }else
        pass1.setEchoChar('*');
    }//GEN-LAST:event_checkboxActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        int check = 0;
        if(pass1.getPassword().length==0){
            JOptionPane.showMessageDialog(null, "Enter Valid Password");
        }
        else if(user.getText().equals("admin123")&&String.valueOf(pass1.getPassword()).equals("123")){
 
         this.setVisible(false);
        new AdminPanel().setVisible(true);   
            }
        else{
            try{
                String username = user.getText();
                String query = "select * from users where username=?";
                PreparedStatement ps = connect.prepareStatement(query);
                ps.setString(1,username);
                ResultSet rs = ps.executeQuery();       
                String password  = null;
                int count = 0;
                while(rs.next()){
                    count++;
                    password = rs.getString("password");
                    System.out.println(password);
                }
                if(count==1){
                    if(password.equals(String.valueOf(pass1.getPassword()))){
                        check = 1;
                    }else{
                        JOptionPane.showMessageDialog(null ,"Invalid Password!");
                    }
                }else{
                    JOptionPane.showMessageDialog(null ,"SORRY you need to register!");
                }
            }
            catch(Exception e){
            }
        }
        if(check==1){
            this.setVisible(false);
            new Booking(user.getText()).setVisible(true);
        }
    }//GEN-LAST:event_loginActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        this.setVisible(false);
        new register().setVisible(true);
        //this.setVisible(true);
        
    }//GEN-LAST:event_signupActionPerformed

    private void pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass1ActionPerformed

    private void userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusGained
        if(user.getText().equals("Enter User ID")){
           user.setText(null);
           user.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_userFocusGained

    private void userFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusLost
        if(user.getText().equals("")){
           user.setForeground(new Color(204,204,204));
           user.setText("Enter User ID");
        }
    }//GEN-LAST:event_userFocusLost

    private void pass1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass1FocusGained
        if(user.getText().equals("Enter Password")){
           user.setText(null);
           user.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_pass1FocusGained

    private void pass1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass1FocusLost
        if(user.getText().equals("")){
           user.setForeground(new Color(0,0,0));
           user.setText("Enter Password");
        }
    }//GEN-LAST:event_pass1FocusLost

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JButton login;
    private javax.swing.JLabel name;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JButton signup;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
